Repository Lyzev/Schizoid, pull requests merged in 2024-06, with the labels that each got.

#98 should work as intended
  src/main/kotlin/dev/lyzev/api/opengl/WrappedFramebuffer.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shader.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
  src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientSlider.kt
  src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientText.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableWaterMark.kt
  src/main/resources/assets/schizoid/shaders/core/GameOfLife/GameOfLife_CP.glsl
Labels: enhancement, high priority

#100 fixed the bug
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shader.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
Labels: bug, high priority

#102 implemented the suggestion
  src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableConfigManager.kt
Labels: enhancement, high priority

#103 set rear view feature as incompatible with iris
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableRearView.kt
Labels: bug, high priority

#105 104 suggestion target hud
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/Module.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableTargetHUD.kt
  src/main/resources/schizoid.accesswidener
Labels: enhancement, high priority

#107 implemented suggestion
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/Module.kt
Labels: enhancement, mid priority

#118 implemented suggestion
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableWaterMark.kt
Labels: enhancement, low priority

#120 implemented Align Modules
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableModules.kt
Labels: enhancement, high priority

#122 migrated Fabric
  gradle/libs.versions.toml
Labels: enhancement, high priority

#124 removed redirect
  src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/MixinMouse.java
  src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/input/MixinKeyboardInput.java
  src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/network/MixinClientPlayerEntity.java
  src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/render/entity/MixinLivingEntityRenderer.java
  src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/util/MixinWindow.java
Labels: enhancement, high priority

#126 fix crash on window resize
  src/main/kotlin/dev/lyzev/api/imgui/render/ImGuiRenderer.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
Labels: bug, high priority

#128 fix no mouse cursor change with other mods
  src/main/kotlin/dev/lyzev/api/imgui/ImGuiLoader.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
Labels: bug, high priority

#130 added initial size and pos
  src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableConfigManager.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/Feature.kt
Labels: enhancement, high priority

#132 possible fix
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
Labels: bug, high priority

#133 did take way too long, sry
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
  src/main/resources/assets/schizoid/shaders/core/Random/Random_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Random/Random_VP.glsl
Labels: bug, high priority

#136 fixed the crash bug
  src/main/kotlin/dev/lyzev/api/theme/OSTheme.kt
Labels: bug, high priority

#138 rewrite shaders
  src/main/kotlin/dev/lyzev/api/imgui/render/ImGuiRenderer.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shader.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/blur/BlurHelper.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableBlur.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableMediaPlayer.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableRearView.kt
  src/main/resources/assets/schizoid/shaders/core/Acrylic/Acrylic_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Acrylic/Acrylic_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/Add/Add_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Add/Add_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/Blend/Blend_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Blend/Blend_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/Box/Box_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Box/Box_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/ColorGrading/ColorGrading_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/ColorGrading/ColorGrading_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/Depth/Depth_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Depth/Depth_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/DualKawaseDown/DualKawaseDown_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/DualKawaseDown/DualKawaseDown_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/DualKawaseUp/DualKawaseUp_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/DualKawaseUp/DualKawaseUp_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/Flip/Flip_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Flip/Flip_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/Gaussian/Gaussian_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Gaussian/Gaussian_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/Kawase/Kawase_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Kawase/Kawase_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/LinearizeDepth/LinearizeDepth_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/LinearizeDepth/LinearizeDepth_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/Mask/Mask_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Mask/Mask_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/MovingAveragesBox/MovingAveragesBox_CP.glsl
  src/main/resources/assets/schizoid/shaders/core/Particle/Particle_CP.glsl
  src/main/resources/assets/schizoid/shaders/core/PassThrough/PassThrough_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/PassThrough/PassThrough_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/Random/Random_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Random/Random_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/Reflection/Reflection_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Threshold/Threshold_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Threshold/Threshold_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/Tint/Tint_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Tint/Tint_VP.glsl
  src/main/resources/assets/schizoid/shaders/include/3DSimplexNoise.glsl
  src/main/resources/assets/schizoid/shaders/include/Acrylic.glsl
  src/main/resources/assets/schizoid/shaders/include/Color.glsl
  src/main/resources/assets/schizoid/shaders/include/Depth.glsl
  src/main/resources/assets/schizoid/shaders/include/Luminance.glsl
  src/main/resources/assets/schizoid/shaders/include/Temperature.glsl
Labels: enhancement, high priority

#139 added toggle sneak feature
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/movement/ModuleToggleableToggleSneak.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/player/ModuleToggleableFastPlace.kt
Labels: enhancement, low priority

#141 added more dev tools
  src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableDeveloperTool.kt
  src/main/kotlin/dev/lyzev/api/opengl/WrappedFramebuffer.kt
  src/main/resources/assets/schizoid/shaders/core/Reflection/Reflection_FP.glsl
Labels: enhancement, mid priority

#143 fixed bug
  src/main/resources/assets/schizoid/shaders/core/Tint/Tint_FP.glsl
Labels: bug, high priority

#144 fixed bug (second try)
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/blur/BlurHelper.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableBlur.kt
  src/main/resources/assets/schizoid/shaders/core/Tint/Tint_FP.glsl
Labels: bug, high priority

#145 added toggle walk feature
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/movement/ModuleToggleableToggleSneak.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/movement/ModuleToggleableToggleWalk.kt
Labels: enhancement, low priority

#147 fixed bug
  src/main/kotlin/dev/lyzev/api/imgui/render/ImGuiRenderer.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shader.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableMediaPlayer.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableRearView.kt
  src/main/resources/assets/schizoid/shaders/core/Add/Add_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Flip/Flip_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Flip/Flip_VP.glsl
  src/main/resources/assets/schizoid/shaders/core/PassThrough/PassThrough_FP.glsl
Labels: bug, high priority

#149 improved developer tool
  src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableDeveloperTool.kt
  src/main/kotlin/dev/lyzev/api/opengl/WrappedFramebuffer.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/blur/blurs/BlurBox.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/blur/blurs/BlurDualKawase.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/blur/blurs/BlurGaussian.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/blur/blurs/BlurKawase.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/blur/blurs/BlurMovingAveragesBox.kt
Labels: enhancement, mid priority

#153 fixed the bug
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/dev/lyzev/api/account/Account.kt
  src/main/kotlin/dev/lyzev/api/account/accounts/AccountCracked.kt
  src/main/kotlin/dev/lyzev/api/account/accounts/AccountEasyMC.kt
  src/main/kotlin/dev/lyzev/api/account/accounts/AccountMicrosoft.kt
  src/main/kotlin/dev/lyzev/api/account/accounts/AccountTheAltening.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenAccountManager.kt
Labels: bug, enhancement, high priority

#155 fixed the bug
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/java/dev/lyzev/schizoid/injection/accessor/MinecraftClientAccessor.java
  src/main/java/dev/lyzev/schizoid/injection/accessor/RealmsAvailabilityAccessor.java
  src/main/java/dev/lyzev/schizoid/injection/mixin/imgui/MixinImGuiImplGlfw.java
  src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/MixinMinecraftClient.java
  src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/MixinMouse.java
  src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/network/MixinClientPlayerEntity.java
  src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/network/MixinClientPlayerInteractionManager.java
  src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/render/MixinCamera.java
  src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/entity/MixinEntity.java
  src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/network/MixinClientConnection.java
  src/main/kotlin/dev/lyzev/api/account/Account.kt
  src/main/kotlin/dev/lyzev/api/account/accounts/AccountCracked.kt
  src/main/kotlin/dev/lyzev/api/account/accounts/AccountEasyMC.kt
  src/main/kotlin/dev/lyzev/api/account/accounts/AccountMicrosoft.kt
  src/main/kotlin/dev/lyzev/api/account/accounts/AccountTheAltening.kt
  src/main/kotlin/dev/lyzev/api/cryptography/cipher/AES.kt
  src/main/kotlin/dev/lyzev/api/cryptography/hwid/HWID.kt
  src/main/kotlin/dev/lyzev/api/events/Events.kt
  src/main/kotlin/dev/lyzev/api/imgui/ImGuiLoader.kt
  src/main/kotlin/dev/lyzev/api/imgui/render/ImGuiRenderer.kt
  src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableConfigManager.kt
  src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableDeveloperTool.kt
  src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableSearch.kt
  src/main/kotlin/dev/lyzev/api/opengl/WrappedFramebuffer.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/blur/BlurHelper.kt
  src/main/kotlin/dev/lyzev/api/setting/SettingInitializer.kt
  src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientMultiText.kt
  src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientSlider.kt
  src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientText.kt
  src/main/kotlin/dev/lyzev/schizoid/Schizoid.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/Feature.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/FeatureManager.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/FeatureImGui.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/ImGuiScreen.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenAccountManager.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/exploit/ModuleToggleablePacketManipulator.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/misc/ModuleToggleableDiscordRichPresence.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/movement/ModuleToggleableToggleSneak.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/movement/ModuleToggleableToggleWalk.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableBlur.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableCloseScreen.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableMediaPlayer.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableMotionGraph.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableRearView.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableTorus.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableWaterMark.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableZoom.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/util/ModuleRunnableDepthTextureScreenshot.kt
  src/main/resources/assets/schizoid/shaders/core/DualKawaseDown/DualKawaseDown_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/DualKawaseUp/DualKawaseUp_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/GameOfLife/GameOfLife_CP.glsl
  src/main/resources/assets/schizoid/shaders/core/Gaussian/Gaussian_FP.glsl
  src/main/resources/assets/schizoid/shaders/include/Temperature.glsl
Labels: bug, enhancement, high priority

#157 added rgb puke mode system
  .github/workflows/release-nightly-build.yml
  .github/workflows/release.yml
  build.gradle.kts
  src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/render/MixinWorldRenderer.java
  src/main/kotlin/dev/lyzev/api/opengl/Render.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shader.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/blur/BlurHelper.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableBlur.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableColorGrading.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableTorus.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/util/ModuleRunnableDepthTextureScreenshot.kt
  src/main/resources/assets/schizoid/shaders/core/Acrylic/Acrylic_FP.glsl
  src/main/resources/assets/schizoid/shaders/core/Tint/Tint_FP.glsl
  src/main/resources/assets/schizoid/shaders/include/RGBPukeCircle.glsl
  src/main/resources/assets/schizoid/shaders/include/RGBPukeNoise.glsl
Labels: enhancement, low priority

#160 bumped to 1.21
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/render/MixinCamera.java
  src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/render/MixinWorldRenderer.java
  src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/render/entity/MixinLivingEntityRenderer.java
  src/main/kotlin/dev/lyzev/api/events/Events.kt
  src/main/kotlin/dev/lyzev/api/opengl/Render.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shader.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
  src/main/kotlin/dev/lyzev/api/opengl/shader/blur/BlurHelper.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableBlur.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableRearView.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableTorus.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableTrueSight.kt
  src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableViewClip.kt
  src/main/resources/assets/schizoid/shaders/core/Depth/Depth_FP.glsl
  src/main/resources/schizoid.accesswidener
Labels: enhancement, high priority

#163 [skip ci]
  README.md
Labels: enhancement, high priority

#164 change build configuration to include transient dependencies
  build.gradle.kts
Labels: bug, high priority
